id: ACA9F4DB6
base_file: f7A8F.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:23:43.091146
  last_modified_at: 2022-06-17 14:23:43.091155
