id: ACA9F4DB6
base_file: f98DF.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:23:43.112443
  last_modified_at: 2022-06-17 14:23:43.112454
