id: ACA9F4DB6
base_file: f8675.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:23:43.097602
  last_modified_at: 2022-06-17 14:23:43.097607
