id: ACA9F4DB6
base_file: fADB3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:23:43.121656
  last_modified_at: 2022-06-17 14:23:43.121666
